# Generated by Django 5.2.2 on 2025-06-22 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_alter_orderdetail_quantity_alter_productcolor_color_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(upload_to='Carousel/', verbose_name='Carousel')),
                ('url', models.URLField(verbose_name='URL')),
            ],
            options={
                'verbose_name': 'carouselimage',
                'verbose_name_plural': 'carouselimages',
            },
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
    ]
