# Generated by Django 5.2.2 on 2025-06-08 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_historicalproduct_updated_at_product_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderdetail',
            options={'verbose_name': 'orderdetail', 'verbose_name_plural': 'order details'},
        ),
        migrations.AddField(
            model_name='historicalproduct',
            name='stock',
            field=models.IntegerField(default=10, verbose_name='Cantidad'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.IntegerField(default=10, verbose_name='Cantidad'),
            preserve_default=False,
        ),
    ]
