# Generated by Django 5.2.2 on 2025-06-22 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_carouselimage_alter_category_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carouselimage',
            name='Image',
            field=models.ImageField(upload_to='media/carousel/', verbose_name='Carousel'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='media/products/', verbose_name='Imagen'),
        ),
    ]
