# Generated by Django 5.2.2 on 2025-06-10 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0004_productimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproduct',
            name='stock',
            field=models.IntegerField(default=0, verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.IntegerField(default=0, verbose_name='Cantidad'),
        ),
    ]
